# Generated by Django 5.0.4 on 2025-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
